# Generated by Django 4.1.7 on 2023-03-25 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fields',
            new_name='Practice_Areas',
        ),
    ]
