# Generated by Django 4.1.7 on 2023-03-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_rename_fields_practice_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice_areas',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1.1),
            preserve_default=False,
        ),
    ]
