# Generated by Django 4.1.7 on 2023-03-25 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_practice_areas_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice_areas',
            name='created_at',
        ),
    ]
