# Generated by Django 4.1.7 on 2023-03-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attorneys', '0002_alter_attorneys_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Happy_Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222)),
                ('job', models.CharField(max_length=222)),
                ('comment', models.TextField()),
            ],
            options={
                'verbose_name': 'Happy_Client',
                'verbose_name_plural': 'Happy_Clients',
            },
        ),
    ]
